import type { Metadata } from "next";
import localFont from "next/font/local";
import { JetBrains_Mono as MonoFont } from "next/font/google";
import "./globals.css";

const sans = localFont({
    src: "./fonts/mona-sans.woff2",
    variable: "--font-sans",
    weight: "400 600 700 800",
});

const mono = MonoFont({
    subsets: ["latin"],
    variable: "--font-mono",
    display: "swap",
    weight: ["400", "500"],
});

export const metadata: Metadata = {
    title: "Ernesto Cassino - Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${sans.variable} ${mono.variable} antialiased`}>
                {children}
            </body>
        </html>
    );
}
